### ISSUE TITLE
Error Building Sample Project

### ISSUE THREAD

**Issue by IkoLogs** [AlexBAV/corsl#1]
Hi

Thank you very much for helping with this lib

I have taken a zip of Corsl, extracted, updated winrt nugget package and sample will not build.

Also tried referencing corsl  in my current project but  corsl::promise is not showing up in corsl name space, even though corsl::future is present.

I am using vs2015, so had to convert build type from version 141 to 140. v2017 too buggy for me currently.

Again the sample does not build for me out of the box, and i only had to update winrt nugget cause that was first thing it complained about .

Thanks Much in advance 

some of the error output

[1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2975	'_Test': invalid template argument for 'std::enable_if_t', expected compile-time constant expression	sample1	d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\promise.h	27	

[2]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		namespace "corsl" has no member "promise"	sample1	d:\Development\Projects\LIBS\Corsl\corsl-master\corsl-master\sample1\main.cpp	238	

cheers

**Comment by AlexBAV** [comment]
Unfortunately, VS 2015 lacks too much to be able to compile `corsl`. As stated in the readme, VS2017 is required.

**Comment by IkoLogs** [comment]
Thanks for the quick update i'll move over to vs2017 try again.

**Comment by IkoLogs** [comment]
Hi

I have fixed my vs2017 by  completing the updates. (would be nice if it showed updates needed in IDE)

But still no promise under corsl:: namespace .

I can see corsl::future but no promise

I have included most corsl headers just to be sure
#include <corsl/all.h>
#include <corsl/shared_future.h>
#include <corsl/future.h>
#include <corsl/compatible_base.h>
#include <corsl/promise.h>

Corsl namespace does not seem to have a promise type.

cheers
Thanks in advance

**Comment by AlexBAV** [comment]
What do you mean by having "no promise"? Could you please provide compiler's output?

**Comment by IkoLogs** [comment]
My declaration 	

corsl future  is found ok 
corsl::future<int> future; // no problem

corsl promise does not seem to exist in corsl namespace
corsl::promise<int> promise;     //i get red lines from VS under this declaration    

compiler 
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0135	namespace "corsl" has no member "promise"	ASL_NATIVE_LIB	d:\Development\Projects\LIBS\Local\ASL_Solution\Projects\ASL_NATIVE_LIB\src\ASL_Foundation.h	1887

I get the red lines in VS soon as i declare  corsl::promise without  even compiling, compilation output is given above. 	

Thanks much

**Comment by AlexBAV** [comment]
Just copy the contents of the Visual Studio's Output window after the build. Not the errors window, please.

**Comment by IkoLogs** [comment]
Hi
error caused by this line of code--->    corsl::promise<int> promise;   
by the way thanks for the detailed samples excellent.


Build output below .

\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\dllmain.cpp(13): warning C4100: 'lpReserved': unreferenced formal parameter
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(43): warning C4005: 'ASL_NATIVE_LIB_EXPORTS': macro redefinition (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(40): note: see previous definition of 'ASL_NATIVE_LIB_EXPORTS' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\dllmain.cpp(10): warning C4100: 'hModule': unreferenced formal parameter
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_nativelib_a.h(79): warning C4100: 'args': unreferenced formal parameter (compiling source file src\ASL_NativeLib_A.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_nativelib_a.h(79): warning C4100: 'sender': unreferenced formal parameter (compiling source file src\ASL_NativeLib_A.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(209): warning C4114: same type qualifier used more than once (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(678): warning C4100: 'other': unreferenced formal parameter (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1295): warning C4100: 'other': unreferenced formal parameter (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\promise.h(27): error C2975: '_Test': invalid template argument for 'std::enable_if_t', expected compile-time constant expression (compiling source file src\ASL_Foundation.cpp)
1>b:\devprograms\visualstudio 2015\vc\include\type_traits(1875): note: see declaration of '_Test' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1887): note: see reference to class template instantiation 'corsl::details::promise<int>' being compiled (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1896): warning C4240: nonstandard extension used: access to 'W_ASL_Native::W_Diagnostics::CEtwLogger::CEtwLogger_ObjConfig' now defined to be 'private', previously it was defined to be 'public' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1730): note: see declaration of 'W_ASL_Native::W_Diagnostics::CEtwLogger::CEtwLogger_ObjConfig' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1912): warning C4240: nonstandard extension used: access to 'W_ASL_Native::W_Diagnostics::CEtwLogger::CEtwLogger_ClassConfig' now defined to be 'private', previously it was defined to be 'public' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.h(1731): note: see declaration of 'W_ASL_Native::W_Diagnostics::CEtwLogger::CEtwLogger_ClassConfig' (compiling source file src\ASL_Foundation.cpp)
1>d:\development\projects\libs\local\asl_solution\projects\asl_native_lib\src\asl_foundation.cpp(14): warning C4114: same type qualifier used more than once
1>Done building project "ASL_NATIVE_LIB.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
cheers

**Comment by AlexBAV** [comment]
Hi. `promise`, as well as `future`, are templates. You need to specify the template parameter when you instantiate those types:

```C++

corsl::future<void> f1;

corsl::future<std::wstring> f2;

corsl::promise<void> p1;

corsl::promise<float> p2;
```

**Comment by IkoLogs** [comment]
HI

Thanks for the update. I mentioned in earlier post thatr i can see future Ok				corsl::future<int> future;   // this  shows in the namespace ok 

but 
corsl::promise<int> promise;  // says this is not in corsl namespace    

In fact as i do corsl::   intellisense shows everything in the corsl library all except except promise.

So before i even atttemp to  call a function, its not even showing in the namespace 
corsl::future<int> future; //this is in the namespace

Thiseditor is removing the angle brackets from my post

Cheers

**Comment by AlexBAV** [comment]
Please use Markdown to mark C++ code you type. Otherwise the parser may "eat" some characters.

**Comment by IkoLogs** [comment]
thanks for the tip about time , cheers

**Comment by IkoLogs** [comment]
`corsl::future<int> future;  //picked up in namespace    
corsl::promise<int> promise;	//says this is not present in Corsl	
`

**Comment by AlexBAV** [comment]
Are you able to compile the included sample (sample1) unmodified?

I have Visual Studio 2017 (Version 15.2 - 26430.12). You can check VS version in Help -> About.

If included sample compiles, but your code does not, check that you specify the following compiler options:

`/await /std:c++latest`

They are required for successful compilation.

**Comment by IkoLogs** [comment]
Thanks for your efforts resolving this.

1. ) Since moving to Vs 2107 just tried sample again builds fine, my previous attempt was vs2015.
2) We are on same version Vs2017 Version 15.2 - 26430.12)
3. I am using cloned Winrt Blocks sample which already contains  `/await /std:c++latest`

This is my first time getting the sample working since move  from vs2015, i will have a play with the sample to see why my project is not picking up corsl::promise. The same line builds in the sample. And i have also copy all headers from sample into my project and still not seeing corsl::promise.

Could the namespace corsl::details::promise have anything to do with this.

cheers

**Comment by AlexBAV** [comment]
Currently `corsl` is used in three large projects here and compiles correctly in all of them.

`corsl` has all stuff in `corsl::details` namespace and then "brings" public stuff back to `corsl` namespace, using `using details::XXX;` declaration.

**Comment by IkoLogs** [comment]
Hi Alex

Thank you very much for your help and again examples have perfect detail.

Problem resolved
After moving to Vs2017  using the same project, my tool chain remained at version 140.
Changed tool chain version to 141 and promise is working in my solution.

My project continues on Vs 2017,  sorry i missed this requirement in your instructions and had to drag you through my upgrade.

Nice utility library Cheers
