### ISSUE TITLE
Corsl does not support "permissive-" mode

### ISSUE THREAD

**Issue by IkoLogs** [AlexBAV/corsl#2]
Hi

I have been getting familiar with this great library playing with the sample project you kindly provided.

Now i  want to utilize Corsl API  in my project.

1. Previously had issue  cause my project was set  to v140 ms toolchain instead of v141
This resolved the problem of promise not appearing in corsl namespace.

2. However on building the code promise variable declaration builds fine but future variable declaration fails.

3. Currently only in corsl sample can i build future and promise ok, not in my project , but also the code snippet below is from unmodified ms cppwinrt sample called Blocks.

4. I am trying to get corsl future to build on a project that support x86/x64/ and ARM. The corsl sample project only supports x86/x64 builds, else i would have used it as my template and move. Dont mind tip if its convertible to support ARM.

5. So as per the title of this post , i have turned my attention to get corsl to build with almost any MS  cpp-WinRt  sample that supports x86/x64/ARM example Blocks, and its failing on future. 

6. Currently MS does not provide a template project for Cpp-WinRt so i have to choose from there samples to clone as base for my project,  tried your sample as clone for my base but  ARM build not supported.

Thanks

//Main of Microsoft cpp-winrt  blocks sample i insert corsl test code 
```C++
#include <corsl/all.h>
int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{


	corsl::future<int> refresh_task; //complier error 
	corsl::promise<int> prom; //builds ok

    CoreApplication::Run(App());
}
```

 Error Output   {  undeclared variable   use_count'} Line 153 future.h

```
1>------ Rebuild All started: Project: LibTestApp, Configuration: Debug x64 ------
1>        1 file(s) copied.
1>pch.cpp
1>App.cpp
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(153): error C2065: 'use_count': undeclared identifier
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(152): note: while compiling class template member function 'void corsl::details::promise_type_<T>::release(void) noexcept'
1>        with
1>        [
1>            T=int
1>        ]
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(236): note: see reference to function template instantiation 'void corsl::details::promise_type_<T>::release(void) noexcept' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(236): note: see reference to class template instantiation 'corsl::details::promise_type_<T>' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(234): note: while compiling class template member function 'corsl::details::future<int>::~future(void)'
1>d:\development\projects\test projects\cppwinrt\corsl_blocks\app.cpp(150): note: see reference to function template instantiation 'corsl::details::future<int>::~future(void)' being compiled
1>d:\development\projects\test projects\cppwinrt\corsl_blocks\app.cpp(150): note: see reference to class template instantiation 'corsl::details::future<int>' being compiled
1>d:\development\projects\test projects\cppwinrt\corsl_blocks\packages\cppwinrt.2017.4.6.1\build\native\include\winrt\base.h(4800): note: see reference to class template instantiation 'winrt::Windows::Foundation::Collections::impl_IIterator<winrt::Windows::Foundation::Collections::IIterator<T>,T>' being compiled
1>        with
1>        [
1>            T=winrt::Windows::UI::Composition::Visual
1>        ]
1>d:\development\projects\test projects\cppwinrt\corsl_blocks\app.cpp(66): note: see reference to class template instantiation 'winrt::Windows::Foundation::Collections::IIterator<T>' being compiled
1>        with
1>        [
1>            T=winrt::Windows::UI::Composition::Visual
1>        ]
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(153): error C2228: left of '.fetch_sub' must have class/struct/union
1>d:\development\projects\libs\corsl\corsl-master\corsl-master\include\corsl\future.h(153): note: type is 'unknown-type'
1>Done building project "LibTestApp.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by AlexBAV** [comment]
It looks like you incorrectly integrate the library into your project. Make sure `corsl\include` path is in your Include locations list.

Look at the sample project - under `sample1` project properties in "VC++ Directories" it has "$(SolutionDir)\include" which points to the required folder.

**Comment by IkoLogs** [comment]
Hi Alex

Thanks for the feedback. it confirmed for me that you never heard such symptoms regards corsl future declaration, so i had to look closer to home for a solution, given that the corsl sample builds.

 I am using quite a number of third party libraries such as boost, poco, and cppwinrt to name a few which all have their path included in c++ include path, now that also  has Corsl/include, and an excellent addition .

The problem for building corsl::future  was "for me" related to /d1permissive- . 

After trying various cpp-winrt projects, i found about 2 out of 6 samples that dont contain /d1permissive- in command line options, usually declared after std latest etc.
example IBuffer cpp-winrt example does not contain permissive.
corsl sample also does not contain permissive.

Took that out and at least now i can build corsl  future and promise declarations.

Thank you very much for your effort with this, the detailed examples  add a lot of value.

cheers

**Comment by AlexBAV** [comment]
I've tried to build the library with permissive mode switched off, but had strange (to my understanding) compilation errors.

Currently, library supported only permissive mode.

**Comment by AlexBAV** [comment]
permissive- is now supported

**Comment by IkoLogs** [comment]
excellent thanks for the update,
